### ISSUE TITLE
Why is the settings Clientside?

### ISSUE THREAD

**Issue by Shaieve** [C0nw0nk/Garrys-Mod-Family-Sharing#9]
https://github.com/C0nw0nk/Garrys-Mod-Family-Sharing/blob/master/garrysmod/lua/autorun/familysharing.lua#L17

People could just be stealing your API if they dumped the server with scripthook or any other stuff, what's the fucking point?

**Comment by Phoenixf129** [comment]
Hey, you're totally wrong. 

Do you know how the client, shared and server states work? 
You're currently using the shared realm, which means you're sending the whole file to the client, regardless of whether it's wrapped in an "if SERVER block". The client just skips over the blocks.

You can do many things with a steam api key, including abusing it so the account gets limited.

Please fix your code.

**Comment by C0nw0nk** [comment]
Like I wrote on the readme page you are all more than welcome to make modifications and make a pull request.

I do not play Garry's mod but if you make a pull request and I see you have split the code into two files one for the client folder and one for the server folder removing it from shared then i will push it to the main repo as an update.
